from __future__ import annotations
from typing import Protocol, Iterator
from kando.schema.events import KandoEvent


class LedgerStore(Protocol):
    def append(self, events: list[KandoEvent]) -> None: ...
    def read(self, from_position: int = 0) -> Iterator[KandoEvent]: ...
    def read_all(self) -> Iterator[KandoEvent]: ...
    def stream_name(self) -> str: ...
